name: manage-azure-policy-8abd5465
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Rally_Deploy_CanNotDelete_Resource_Lock_48fab193-c486-443e-a306-3a189c70281c/**'
#      - .github/workflows/manage-azure-policy-8abd5465.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_8abd5465}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Rally_Deploy_CanNotDelete_Resource_Lock_48fab193-c486-443e-a306-3a189c70281c/**
